project:
  type: website
  output-dir: docs

website:
  title: "Ryan McWay"
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Bio
      - href: cv.qmd
        text: CV
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: fieldwork.qmd
        text: Fieldwork
      - href: data-packages.qmd
        text: Data & Packages

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true



